Python way

In [1]:
ls = [1,2,3,4,5]

r = [val + 1 for val in ls]
r

[2, 3, 4, 5, 6]

Numpy way

In [3]:
import numpy as np

arr = np.array(ls)
r = arr + 1
r

array([2, 3, 4, 5, 6])

### Ufuncs

In [30]:
ls = list(range(100000))
%timeit [val + 5 for val in ls]

6.21 ms ± 60.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
arr = np.array(ls)
%timeit arr + 5

33.4 µs ± 611 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Aggregations

In [34]:
from random import random
ls = [random() for i in range(100000)]
%timeit min(ls)

1.28 ms ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [35]:
arr = np.array(ls)
%timeit arr.min()

33.7 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [50]:
M = np.random.randint(0, 10, (3, 5))
M

array([[5, 8, 5, 0, 6],
       [7, 7, 2, 0, 4],
       [6, 5, 9, 7, 2]])

In [53]:
M.sum()

73

In [51]:
M.sum(axis=0)

array([18, 20, 16,  7, 12])

In [52]:
M.sum(axis=1)

array([24, 20, 29])

Masking

In [8]:
ls = np.array([1, 2, 3, 4, 5])
print(ls)

mask = np.array([False, False, True, True, True])
print(ls[mask])

[1 2 3 4 5]
[3 4 5]


In [9]:
ls = np.array([1, 2, 3, 4, 5])
mask = (ls % 2 ==0) | (ls > 4)
ls[mask]

array([2, 4, 5])

Fancy indexing

In [11]:
ls = np.array([1, 2, 3, 4, 5])
index_to_select = [0, 1]
ls[index_to_select]

array([1, 2])

Combine with multi-dimensional arrays:

In [20]:
m = np.arange(6).reshape(2, 3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# Ask for row 0 and column 1
m[0, 1]

1

Masking multi-dimensional arrays:

In [22]:
m = np.arange(6).reshape(2, 3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
m[abs(m-3)<2]

array([2, 3, 4])

Mix masking and slicing:

In [24]:
m = np.arange(6).reshape(2, 3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
m[m.sum(axis=1) > 4]

array([[3, 4, 5]])

In [25]:
m[m.sum(axis=1) > 4, 1:]

array([[4, 5]])

Quick start to Numpy

In [28]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])