Creating Arrays

1-D Arrays

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

2-D Arrays

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

3-D arrays

In [32]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Array Indexing

In [33]:
arr = np.array([1, 2, 3, 4])

# Get the first element from the following array
arr[0]

1

In [34]:
# Get third and fourth elements from the following array and add them.
arr[2] + arr[3]

7

Array Slicing

We get a slice of an array like this: `[start:end]`.

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 1 to index 5 from the following array
arr[1:5]

array([2, 3, 4, 5])

In [36]:
# Slice elements from index 4 to the end of the array
arr[4:]

array([5, 6, 7])

In [37]:
# Slice elements from the beginning to index 4 (not included)
arr[:4]

array([1, 2, 3, 4])

Get the Shape of an Array

In [38]:
# Create a 2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
# returns (2, 4), which means that the array has 2 dimensions, 
# the first dimension has 2 elements and the second has 4.
arr.shape

(2, 4)

Reshaping arrays

Reshape from 1-D to 2-D

In [40]:
# Create a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
# Convert the 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements
new_arr = arr.reshape(4, 3)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Reshape From 1-D to 3-D

In [42]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
new_arr = arr.reshape(2, 3, 2)
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])